apiVersion: v1
kind: Secret
metadata:
  name: kiunzi-gateway-secrets
type: Opaque
stringData:
  auth-server-url: https://<your_keycloak_hostname>/realms/quarkus
  client-id: <your_keycloak_client_id>
  client-secret: <your_keycloak_client_secret>
  role-claim-path: realm_access/roles,resource_access/<your_keycloak_client_id>/roles
  token-role: user
  token-subject: service