apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: client-certificate
spec:
  isCA: false
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
    - jasonmarston
  commonName: client
  dnsNames:
  - client
  secretName: client-secrets
  usages:
  - client auth
  privateKey:
    rotationPolicy: Always
    encoding: PKCS8
    algorithm: RSA
    size: 2048
  issuerRef:
    name: ca-issuer
    kind: Issuer
    group: cert-manager.io