apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secrets
  namespace: default
type: Opaque
stringData:
  keycloak-hostname: <your_keycloak_hostname>
  keycloak-admin-name: <your_keycloak_admin_username>
  keycloak-admin-password: <your_keycloak_admin_password>
  keycloak-db-provider: mysql
  keycloak-db-url: jdbc:mysql://mysql.default.svc.cluster.local:3306/keycloak
  keycloak-db-user: <your_keycloak_db_user>
  keycloak-db-password: <your_keycloak_db_password>