apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: login-demo-certificate
  namespace: istio-system
spec:
  issuerRef:
    name: letsencrypt-issuer
  secretName: login-demo-secrets
  commonName: login.demo.jasonmarston.co.uk
  dnsNames:
  - login.demo.jasonmarston.co.uk