apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-claim
  namespace: default
spec:
  storageClassName: database
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
