apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
  namespace: default
type: Opaque
stringData:
  mysql-root-password: <mysql_root_password>
  mysql-database: keycloak
  mysql-user: <your_keycloak_db_user>
  mysql-password: <your_keycloak_db_password>
