apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: login-demo-certificate
  namespace: istio-system
spec:
  issuerRef:
    name: letsencrypt-issuer
  secretName: login-demo-secrets
  commonName: <your_keycloak_hostname>
  dnsNames:
  - <your_keycloak_hostname>