apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ca-certificate
  namespace: istio-system
spec:
  isCA: true
  duration: 8760h # 365d
  renewBefore: 2920h # 121d
  subject:
    organizations:
    - jasonmarston
  commonName: ca-certificate
  dnsNames:
    - ca-certificate
  secretName: ca-secret
  privateKey:
    rotationPolicy: Always
    encoding: PKCS8
    algorithm: RSA
    size: 2048
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
    group: cert-manager.io